# Generated by Django 3.2.6 on 2021-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210825_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
